export enum EffectType {
  DAMAGE = 'DAMAGE',
  HEAL = 'HEAL',
  SHIELD = 'SHIELD',
  BUFF = 'BUFF',
  DEBUFF = 'DEBUFF',
  POISON = 'POISON',
  BURN = 'BURN',
  FREEZE = 'FREEZE',
  STUN = 'STUN',
  SPEED_UP = 'SPEED_UP',
  SPEED_DOWN = 'SPEED_DOWN',
  ATTACK_UP = 'ATTACK_UP',
  ATTACK_DOWN = 'ATTACK_DOWN',
  DEFENSE_UP = 'DEFENSE_UP',
  DEFENSE_DOWN = 'DEFENSE_DOWN'
} 